#! /bin/sh

install_puppet() {
	cd /etc/yum.repos.d

	if [ ! -s "puppetlabs.repo" ]
	then
		curl -O https://raw.github.com/nrr/miscellaneous-provisioning-tools/yum.repos.d/puppetlabs.repo
	fi

	yum -y update
	yum -y install puppet
}

install_daemontools_service() {
	local $td=`mktemp -d XXXXXXX`
	mkdir -p /usr/local/etc/services/puppet_client
	curl -LsSf https://github.com/nrr/daemontools-service-puppet-client/tarball/master | tar -C $td -zxvf -
	rsync -rPv --delete $td/nrr-daemontools-service-puppet-client*/. /usr/local/etc/services/puppet_client/.
	chown -R root:root /usr/local/etc/services/puppet_client/.
	ln -s /usr/local/etc/services/puppet_client /service/puppet_client
}

perform_initial_repository_clone() {
	mkdir /service/puppet_client/root/sandbox/domains/github.com/nrr/
	pushd /service/puppet_client/root/sandbox/domains/github.com/nrr/
	git clone git@github.com:nrr/miscellaneous-provisioning-tools
	rsync -rPv ./miscellaneous-provisioning-tools/puppet/. /service/puppet_client/root/puppet/.
	popd
}

stand_up_daemontools_service() {
	svc -o /service/puppet_client
}

install_puppet
perform_initial_repository_clone
stand_up_daemontools_service
